---
Name: mysiteconfig
After: 'framework/*','cms/*'
---
SiteTree:
  nested_urls: 1
  extensions:
   - WorkflowEmbargoExpiryExtension
SSViewer:
  theme: 'default'
MySQLDatabase:
  connection_charset: 'utf8'
LeftAndMain:
  help_link: "https://www.cwp.govt.nz/user-help/"
