---
Name: mysiteconfig
After: 'framework/*','cms/*'
---
SiteTree:
  nested_urls: 1
  extensions:
   - WorkflowEmbargoExpiryExtension
SSViewer:
  theme: 'default'
MySQLDatabase:
  connection_charset: 'utf8'

