---
Name: mycwpsite
---
SilverStripe\View\SSViewer:
  themes:
    - 'starter'
    - '$default'
SilverStripe\Admin\LeftAndMain:
  help_link: "https://www.cwp.govt.nz/user-help/"
SilverStripe\Control\Email:
  admin_email: 'no-reply@cwp.govt.nz'